<?php

namespace SuperHero\Bundle\AppBundle\Repository;
use SuperHero\Bundle\AppBundle\Entity\Image;

/**
 * ImageSuperheroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageSuperheroRepository extends \Doctrine\ORM\EntityRepository
{
    public function save(Image $image)
    {
        $this->_em->persist($image);
        $this->_em->flush();
    }
}
