<?php

namespace SuperHero\Bundle\AppBundle\Repository;
use SuperHero\Bundle\AppBundle\Entity\ImageSuperhero;

/**
 * ImageSuperheroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageSuperheroRepository extends \Doctrine\ORM\EntityRepository
{
    public function save(ImageSuperhero $imageSuperhero)
    {
        $this->_em->persist($imageSuperhero);
        $this->_em->flush();
    }
}
