<?php

namespace SuperHero\Bundle\AppBundle\Repository;

/**
 * SuperheroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuperheroRepository extends \Doctrine\ORM\EntityRepository
{
}
